###################################################################
#  _   _ _____   _____                                          _ #
# | \ | |  __ \ / ____|                                        | |#
# |  \| | |__) | |     ___  _ __ ___  _ __ ___   __ _ _ __   __| |#
# | . ` |  ___/| |    / _ \| '_ ` _ \| '_ ` _ \ / _` | '_ \ / _` |#
# | |\  | |    | |____ (_) | | | | | | | | | | | (_| | | | | (_| |#
# |_| \_|_|     \_____\___/|_| |_| |_|_| |_| |_|\__,_|_| |_|\__,_|#
###################################################################

# DO NOT CHANGE VERSION! For internal use.
version: 1.0-SNAPSHOT

commandOnHit: "say Command Executed."

NPCs:
  npc1: # You can use any name here.
    id: 1 # Use the ID of the citizen (/npc select to get it)
    command: "say Hello World! (NPC 1)" # Command you want to execute with NO "/"!
  npc2:
    id: 2
    command: "say Hello World! (NPC 2)"
  npc3:
    id: 3
    command: "say Hello World! (NPC 3)"